### ISSUE TITLE
TWiRF 14

### ISSUE THREAD

**Issue by gnunicorn** [RustFestEU/2016.rustfest.eu#40]
Some thing that happened this week, and should be included
- [ ] ThoughtWorks is sponsoring 
- [ ] New Crypto Workshop by Ethcore (link to https://activities.rustfest.eu/activities/1 for sign up)
- [ ] (New Web Development Workshop by 1AIM)
- [ ] Ryan will be MC'ing – how awesome is that?!?

**Comment by dns2utf8** [comment]
Do you have a Fahrplan for the talks yet or can you say something about it?

**Comment by gnunicorn** [comment]
@dns2utf8 we are hoping to announce them with this edition, too. but need to agree on final scheddule with speakers, MC and team – so no promises.
