### ISSUE TITLE
Change "War stories"

### ISSUE THREAD

**Issue by badboy** [RustFestEU/2016.rustfest.eu#5]
I don't like "war stories" in this context: https://github.com/RustFestEU/rustfest.eu/commit/8267fd3080225189739ed58bb9c029380eb79187#commitcomment-17473421

**Comment by gnunicorn** [comment]
I agree on poor wording here. If we can't find a better terminology I am also fine with just removing that one entirely.

@badboy do you have an alternative proposal or do you prefer removing?

@skade something to fix in the review tomorrow?!

**Comment by skade** [comment]
I just removed the "war"

**Comment by badboy** [comment]
Seems enough. :shipit:
